// Generated by CoffeeScript 2.4.1
(function () {
  var init;

  init = function () {
    var COLORS, Canvas, canvasBig, canvasSmall, i, j, randomNumber;
    COLORS = ['red', 'blue', 'green', 'yellow', 'black'];
    Canvas = class Canvas {
      constructor(idElement, width, height) {
        this.element = document.getElementById(idElement);
        this.ctx = this.element.getContext('2d');
        this.element.width = width;
        this.element.height = height;
      }

      drawStar(x, y, r, p, m, color) {
        var item, j, ref;
        this.ctx.save();
        this.ctx.beginPath();
        this.ctx.translate(x, y);
        this.ctx.moveTo(0, 0 - r);

        for (item = j = 0, ref = p; 0 <= ref ? j < ref : j > ref; item = 0 <= ref ? ++j : --j) {
          this.ctx.rotate(Math.PI / p);
          this.ctx.lineTo(0, 0 - r * m);
          this.ctx.rotate(Math.PI / p);
          this.ctx.lineTo(0, 0 - r);
        }

        this.ctx.fillStyle = color;
        this.ctx.fill();
        return this.ctx.restore();
      }

    };
    canvasBig = new Canvas('canvasBig', 600, 600);
    canvasSmall = new Canvas('canvasSmall', 600, 100);

    randomNumber = function () {
      return Math.floor(Math.random() * 500) + 50;
    };

    for (i = j = 0; j < 5; i = ++j) {
      canvasBig.drawStar(randomNumber(), randomNumber(), 50, 5, 0.4, COLORS[i]);
    }

    return canvasBig.element.addEventListener('click', function (e) {
      var a, b, ctx, g, imageData, r;
      ctx = this.getContext('2d');
      imageData = ctx.getImageData(e.pageX, e.pageY, 1, 1);
      r = imageData.data[0];
      g = imageData.data[1];
      b = imageData.data[2];
      a = imageData.data[3] / 255;
      return canvasSmall.element.style.backgroundColor = `rgba(${r},${g},${b},${a})`;
    });
  };

  window.onload = init;
}).call(this);